### ISSUE TITLE
User Story: Delete a job posting

### ISSUE THREAD

**Issue by steve-doc** [steve-doc/axiom#10]
## Epic #1

As a **User or staff member** I want to **be able to delete a job post** so that I can **remove job posts that are no longer valid**

## Tasks

* [ ] Create View
* [ ] Create route
* [ ] Create control on form that only post creator or staff can delete posts
* [ ] Check if user is sure they want to delete
* [ ] Remove post from list of jobs

## Acceptance Criteria

Only user or staff can see delete button and complete the task
Post is removed from list of jobs/database
