### ISSUE TITLE
User Story: Site navigation

### ISSUE THREAD

**Issue by steve-doc** [steve-doc/axiom#11]
## Epic #9

As a **User** I want to **engage with navigation bar** so that I can **easily move from page to page**

## Tasks

* [ ] Create base template
* [ ] Create main navbar on left for navigating between main pages
* [ ] Create right hand navbar for registration, login, profile and job posts
* [ ] Set control that Post job only appears after login
* [ ] Add logo that links to home page
* [ ] Setup switch to navigation burger button for responsiveness
* [ ] Set up footer navigation

## Acceptance Criteria

All navigation buttons take to correct page
Post job only appears after login
Function on mobile device
