### ISSUE TITLE
User Story: Register as new user

### ISSUE THREAD

**Issue by steve-doc** [steve-doc/axiom#12]
## Epic #2

As a **first time visitor** I want to **be able to register on the site** so that I can **create and edit job posts**

## Tasks

* [ ] Set up user registration view
* [ ] Set up route
* [ ] Create user model
* [ ] Create profile picture model
* [ ] Create template
* [ ] Setup cloudinary for storing profile images

## Acceptance Criteria

User can enter username, password and names, also upload profile image
Check that this is stored and available in profile link
