### ISSUE TITLE
User Story: Register new user

### ISSUE THREAD

**Issue by steve-doc** [steve-doc/axiom#14]
## Epic #2

As a **User** I want to **be able to register for the site** so that I can **login in and create job posts**

## Tasks

* [ ] Create Users App
* [ ] Create profile model
* [ ] Create register view
* [ ] Create register route
* [ ] Create register template

## Acceptance Criteria

A new user can register with username, password, email, profile picture and name details.
