### ISSUE TITLE
User Story: Logout

### ISSUE THREAD

**Issue by steve-doc** [steve-doc/axiom#16]
## Epic #2

As a **User** I want to **log out from site** so that I can **others cannot edit my information**

## Tasks

* [ ] Create logout view
* [ ] Create logout route
* [ ] hid logout button from nav when users are not logged in

## Acceptance Criteria

User can logout and there cannot edit posts or profile until logged back in
