### ISSUE TITLE
User Story: Introduction to services

### ISSUE THREAD

**Issue by steve-doc** [steve-doc/axiom#19]
## Epic #7 

As a **User** I want to **see some short messages explaining the company service** so that I can **decide which service are relevant to me**

## Tasks

* [ ] Create individual cards for each service
* [ ] Add relevant picture to each card
* [ ] Add more info button linked to specific image on services page

## Acceptance Criteria

User can view each service description with appropriate image and click on button that take them to more detail description on services page.
