### ISSUE TITLE
User Story: Services page content

### ISSUE THREAD

**Issue by steve-doc** [steve-doc/axiom#26]
- Epic #8 

As a **User** I want to **view services descriptions** so that I can **understand what the company can do for me**

## Tasks

* [x] Create services route
* [x] Create services Template
* [x] Create individual service description cards for each service

## Acceptance Criteria

User can navigate to page and read all of the individual service descriptions
