### ISSUE TITLE
User Story: Edit Job Post

### ISSUE THREAD

**Issue by steve-doc** [steve-doc/axiom#4]
## Epic #1

As a **User or staff member** I want to **be able to edit the content of a job post** so that I can **display the most up to date information**

## Tasks

* [ ] implement controls to only allow post creator or staff to be able to edit post
* [ ] Add update buttons in job post form
* [ ] Create view to post updated post to the database and return to job view

## Acceptance Criteria

User can open a post have the ability to edit and repost.
Check that post data has been updated as expected
