### ISSUE TITLE
User Story: display list of open jobs

### ISSUE THREAD

**Issue by steve-doc** [steve-doc/axiom#5]
## Epic #1

As a **User or staff member** I want to **view a list of jobs** so that I can **decide which jobs I want to engage with**

## Tasks

* [ ] Create a view and route for this functionality
* [ ] Create a template that displays all available jobs
* [ ] Enable the ability to click on job to drill into detail
* [ ] Add pagination limiting number of jobs to 5 per page

## Acceptance Criteria

To successfully view a list of jobs
To be able to click on any of the jobs
To have usable pagination to look at further jobs
